config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'store/index'

  resources :listings

  get 'pages/about'

  get 'pages/contact'

   root "store#index",as: 'store'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

    private
      def set_locale
        I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
      end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description,:image_url, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    listado = ["UNO", "DOS", "TRES", "CUATRO"]
    @listado = listado
  end

  def contact
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Listing.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages= resource.errors.full_messages.map { |msg| content_tag(:li, msg)}.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4>#{sentence}</h4>
        #{messages}
    </div>
    HTML

    html.html_safe
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="nav-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to store_path, class: "navbar-brand" do%>
        <%= image_tag("bitsket_logo.png", :class=>"img_logo") %>
      <% end %>
    </div><!--navbar header-->
    <!--aqui van todos los links para el boton toggle-->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to pages_about_path do%><i class="glyphicon glyphicon-info-sign"></i><% end %> </li>
        <li><%= link_to pages_contact_path do%><i class="fa fa-twitter"></i><% end %> </li>
        <% if user_signed_in?%>
          <li><%= link_to edit_user_registration_path do%><i class="glyphicon glyphicon-cog"></i><% end %> </li>
          <li><%= link_to destroy_user_session_path, method: :delete do%><i class="glyphicon glyphicon-off"></i><% end %> </li>
        <% else %>
          <li><%= link_to new_user_session_path do%><i class="glyphicon glyphicon-user"></i><% end %> </li>
          <li><%= link_to new_user_registration_path do%><i class="fa fa-edit"></i><% end %> </li>
        <%end%>
      </ul>

    </div><!--navbar collapse-->
  </div><!--container fluid-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBitsket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "favicon.ico" %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String)%>
    
      <div class="alert alert-<%= name == "notice" ? "success":"danger"%> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id=>"flash_#{name}"%>
      </div>
    <% end %>
  
  <% end %>
  <%= yield %>
</div>

 

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Producto Nuevo</h3>
      </div>
      <div class="panel-body">
      
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image_url %><br>
          <%= f.text_field :image_url, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %><br>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      
      
      </div>
    </div> 

<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<table class="table">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= image_tag(listing.image_url) %></td>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>Agrega un producto</h1>

<div class="container">
  <%= render 'form' %>

  <%= link_to 'Back', listings_path %>
</div>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @listing.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/about.html.erb
<h1>Bitsket es el primer mercado mexicano de Bitcoin</h1>
<p>Para comprar y vender lo que sea* de persona a persona </p>

<ul>
<% @listado.each do |l|%>
  <li><%= l %></li>
<% end %>
</ul>

app/views/pages/contact.html.erb
<h1>Escribenos a <a href="https://twitter.com/bitsket/">@bitsket </a></h1>
<p>Eso es en twitter</p>

app/views/store/index.html.erb
<% @products.each do |product|%>
  <div class="col-sm-6 col-md-2">
      <div class="thumbnail">
        <%= image_tag product.image_url%>
        <div class="caption">
          <h3><%= product.name %></h3>
          <p><%= sanitize product.description %></p>
    
          <div class="price">
            <span class="price"><%= number_to_currency product.price, :unit=>'$' %> </span>
          </div>
          <p>
            <a href="#" class="btn btn-primary" role="button">Button</a> 
            <a href="#" class="btn btn-default" role="button">Button</a>
          </p>
        </div>
      </div>
    </div>
<% end %>